
dofile(minetest.get_modpath("chemistry").."/items.lua")
dofile(minetest.get_modpath("chemistry").."/distiller.lua")
dofile(minetest.get_modpath("chemistry").."/grinding_recipes.lua")
dofile(minetest.get_modpath("chemistry").."/acetylene_burner.lua")
dofile(minetest.get_modpath("chemistry").."/carbide_lamp.lua")
dofile(minetest.get_modpath("chemistry").."/molecular_crafting.lua")
dofile(minetest.get_modpath("chemistry").."/ores.lua")
dofile(minetest.get_modpath("chemistry").."/alloy_recipes.lua")
dofile(minetest.get_modpath("chemistry").."/crafts.lua")
dofile(minetest.get_modpath("chemistry").."/periodic_table.lua")
dofile(minetest.get_modpath("chemistry").."/distiller_recipes.lua")
dofile(minetest.get_modpath("chemistry").."/acetylene_burner_recipes.lua")
dofile(minetest.get_modpath("chemistry").."/molecular_crafting_recipes.lua")
dofile(minetest.get_modpath("chemistry").."/air_collector.lua")
dofile(minetest.get_modpath("chemistry").."/gas_condenser.lua")