register_molecular_crafting_recipe ("chemistry:silicon",2, "",0,"technic:silicon_wafer",1,"chemistry:test_tube",2)
register_molecular_crafting_recipe ("default:cobble",1, "",0,"default:cobble",1,"default:cobble",1)
register_molecular_crafting_recipe ("chemistry:copper",1, "",0,"default:copper_ingot",1,"chemistry:test_tube",1)
register_molecular_crafting_recipe ("chemistry:iron",1, "",0,"default:steel_ingot",1,"chemistry:test_tube",1)
register_molecular_crafting_recipe ("chemistry:silver",1, "",0,"moreores:silver_ingot",1,"chemistry:test_tube",1)
register_molecular_crafting_recipe ("chemistry:gold",1, "",0,"default:gold_ingot",1,"chemistry:test_tube",1)
register_molecular_crafting_recipe ("chemistry:aluminum",1, "",0,"chemistry:aluminum_ingot",1,"chemistry:test_tube",1)